# Generated by Django 5.0.7 on 2024-08-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drinks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drink",
            name="image",
            field=models.ImageField(
                default="images/coffeeTwo.png", upload_to="images/"
            ),
        ),
    ]
